// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: registrationconfig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Salt1      string   `protobuf:"bytes,2,opt,name=salt1,proto3" json:"salt1,omitempty"`
	Salt2      []byte   `protobuf:"bytes,3,opt,name=salt2,proto3" json:"salt2,omitempty"`
	Bootstraps []string `protobuf:"bytes,4,rep,name=bootstraps,proto3" json:"bootstraps,omitempty"`
	UhmAddr    string   `protobuf:"bytes,5,opt,name=uhmAddr,proto3" json:"uhmAddr,omitempty"`
	Labels     []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registrationconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_registrationconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_registrationconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Config) GetSalt1() string {
	if x != nil {
		return x.Salt1
	}
	return ""
}

func (x *Config) GetSalt2() []byte {
	if x != nil {
		return x.Salt2
	}
	return nil
}

func (x *Config) GetBootstraps() []string {
	if x != nil {
		return x.Bootstraps
	}
	return nil
}

func (x *Config) GetUhmAddr() string {
	if x != nil {
		return x.UhmAddr
	}
	return ""
}

func (x *Config) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_registrationconfig_proto protoreflect.FileDescriptor

var file_registrationconfig_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x62,
	0x22, 0x9c, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x32, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x68, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x68, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registrationconfig_proto_rawDescOnce sync.Once
	file_registrationconfig_proto_rawDescData = file_registrationconfig_proto_rawDesc
)

func file_registrationconfig_proto_rawDescGZIP() []byte {
	file_registrationconfig_proto_rawDescOnce.Do(func() {
		file_registrationconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_registrationconfig_proto_rawDescData)
	})
	return file_registrationconfig_proto_rawDescData
}

var file_registrationconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registrationconfig_proto_goTypes = []interface{}{
	(*Config)(nil), // 0: registration.util.pb.Config
}
var file_registrationconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_registrationconfig_proto_init() }
func file_registrationconfig_proto_init() {
	if File_registrationconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_registrationconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registrationconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registrationconfig_proto_goTypes,
		DependencyIndexes: file_registrationconfig_proto_depIdxs,
		MessageInfos:      file_registrationconfig_proto_msgTypes,
	}.Build()
	File_registrationconfig_proto = out.File
	file_registrationconfig_proto_rawDesc = nil
	file_registrationconfig_proto_goTypes = nil
	file_registrationconfig_proto_depIdxs = nil
}
