// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: keypair.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignKey []byte `protobuf:"bytes,1,opt,name=signKey,proto3" json:"signKey,omitempty"`
	VerfKey []byte `protobuf:"bytes,2,opt,name=verfKey,proto3" json:"verfKey,omitempty"`
}

func (x *KeyPair) Reset() {
	*x = KeyPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keypair_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair) ProtoMessage() {}

func (x *KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_keypair_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair.ProtoReflect.Descriptor instead.
func (*KeyPair) Descriptor() ([]byte, []int) {
	return file_keypair_proto_rawDescGZIP(), []int{0}
}

func (x *KeyPair) GetSignKey() []byte {
	if x != nil {
		return x.SignKey
	}
	return nil
}

func (x *KeyPair) GetVerfKey() []byte {
	if x != nil {
		return x.VerfKey
	}
	return nil
}

var File_keypair_proto protoreflect.FileDescriptor

var file_keypair_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x73, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x66,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x76, 0x65, 0x72, 0x66, 0x4b,
	0x65, 0x79, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keypair_proto_rawDescOnce sync.Once
	file_keypair_proto_rawDescData = file_keypair_proto_rawDesc
)

func file_keypair_proto_rawDescGZIP() []byte {
	file_keypair_proto_rawDescOnce.Do(func() {
		file_keypair_proto_rawDescData = protoimpl.X.CompressGZIP(file_keypair_proto_rawDescData)
	})
	return file_keypair_proto_rawDescData
}

var file_keypair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keypair_proto_goTypes = []interface{}{
	(*KeyPair)(nil), // 0: pb.KeyPair
}
var file_keypair_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keypair_proto_init() }
func file_keypair_proto_init() {
	if File_keypair_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keypair_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keypair_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keypair_proto_goTypes,
		DependencyIndexes: file_keypair_proto_depIdxs,
		MessageInfos:      file_keypair_proto_msgTypes,
	}.Build()
	File_keypair_proto = out.File
	file_keypair_proto_rawDesc = nil
	file_keypair_proto_goTypes = nil
	file_keypair_proto_depIdxs = nil
}
