// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: votingmanager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priv     []byte `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	Sign     []byte `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Verf     []byte `protobuf:"bytes,3,opt,name=verf,proto3" json:"verf,omitempty"`
	IpfsDir  string `protobuf:"bytes,4,opt,name=ipfsDir,proto3" json:"ipfsDir,omitempty"`
	StoreDir string `protobuf:"bytes,5,opt,name=storeDir,proto3" json:"storeDir,omitempty"`
}

func (x *ManIdentity) Reset() {
	*x = ManIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votingmanager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManIdentity) ProtoMessage() {}

func (x *ManIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_votingmanager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManIdentity.ProtoReflect.Descriptor instead.
func (*ManIdentity) Descriptor() ([]byte, []int) {
	return file_votingmanager_proto_rawDescGZIP(), []int{0}
}

func (x *ManIdentity) GetPriv() []byte {
	if x != nil {
		return x.Priv
	}
	return nil
}

func (x *ManIdentity) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ManIdentity) GetVerf() []byte {
	if x != nil {
		return x.Verf
	}
	return nil
}

func (x *ManIdentity) GetIpfsDir() string {
	if x != nil {
		return x.IpfsDir
	}
	return ""
}

func (x *ManIdentity) GetStoreDir() string {
	if x != nil {
		return x.StoreDir
	}
	return ""
}

var File_votingmanager_proto protoreflect.FileDescriptor

var file_votingmanager_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x2e, 0x70, 0x62, 0x22, 0x7f, 0x0a, 0x0b, 0x4d, 0x61, 0x6e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x69, 0x76, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x70, 0x72, 0x69, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x76, 0x65, 0x72, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x76, 0x65, 0x72, 0x66,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x70, 0x66, 0x73, 0x44, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x70, 0x66, 0x73, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_votingmanager_proto_rawDescOnce sync.Once
	file_votingmanager_proto_rawDescData = file_votingmanager_proto_rawDesc
)

func file_votingmanager_proto_rawDescGZIP() []byte {
	file_votingmanager_proto_rawDescOnce.Do(func() {
		file_votingmanager_proto_rawDescData = protoimpl.X.CompressGZIP(file_votingmanager_proto_rawDescData)
	})
	return file_votingmanager_proto_rawDescData
}

var file_votingmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_votingmanager_proto_goTypes = []interface{}{
	(*ManIdentity)(nil), // 0: voting.util.pb.ManIdentity
}
var file_votingmanager_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_votingmanager_proto_init() }
func file_votingmanager_proto_init() {
	if File_votingmanager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_votingmanager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_votingmanager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_votingmanager_proto_goTypes,
		DependencyIndexes: file_votingmanager_proto_depIdxs,
		MessageInfos:      file_votingmanager_proto_msgTypes,
	}.Build()
	File_votingmanager_proto = out.File
	file_votingmanager_proto_rawDesc = nil
	file_votingmanager_proto_goTypes = nil
	file_votingmanager_proto_depIdxs = nil
}
