// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: votingconfig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Time       *TimeInfo    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Salt1      string       `protobuf:"bytes,3,opt,name=salt1,proto3" json:"salt1,omitempty"`
	Salt2      []byte       `protobuf:"bytes,4,opt,name=salt2,proto3" json:"salt2,omitempty"`
	Candidates []*Candidate `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	ManCid     string       `protobuf:"bytes,6,opt,name=manCid,proto3" json:"manCid,omitempty"`
	PubKey     []byte       `protobuf:"bytes,7,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Params     *Params      `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`
	Type       int32        `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	HkmAddr    string       `protobuf:"bytes,10,opt,name=hkmAddr,proto3" json:"hkmAddr,omitempty"`
	IvmAddr    string       `protobuf:"bytes,11,opt,name=ivmAddr,proto3" json:"ivmAddr,omitempty"`
	Labels     []string     `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votingconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_votingconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_votingconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Config) GetTime() *TimeInfo {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Config) GetSalt1() string {
	if x != nil {
		return x.Salt1
	}
	return ""
}

func (x *Config) GetSalt2() []byte {
	if x != nil {
		return x.Salt2
	}
	return nil
}

func (x *Config) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *Config) GetManCid() string {
	if x != nil {
		return x.ManCid
	}
	return ""
}

func (x *Config) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Config) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Config) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Config) GetHkmAddr() string {
	if x != nil {
		return x.HkmAddr
	}
	return ""
}

func (x *Config) GetIvmAddr() string {
	if x != nil {
		return x.IvmAddr
	}
	return ""
}

func (x *Config) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TimeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Begin string `protobuf:"bytes,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Loc   string `protobuf:"bytes,3,opt,name=loc,proto3" json:"loc,omitempty"`
}

func (x *TimeInfo) Reset() {
	*x = TimeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votingconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInfo) ProtoMessage() {}

func (x *TimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_votingconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInfo.ProtoReflect.Descriptor instead.
func (*TimeInfo) Descriptor() ([]byte, []int) {
	return file_votingconfig_proto_rawDescGZIP(), []int{1}
}

func (x *TimeInfo) GetBegin() string {
	if x != nil {
		return x.Begin
	}
	return ""
}

func (x *TimeInfo) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *TimeInfo) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

type Candidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group   string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Url     string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Image   []byte `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ImgName string `protobuf:"bytes,5,opt,name=imgName,proto3" json:"imgName,omitempty"`
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votingconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_votingconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_votingconfig_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Candidate) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Candidate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Candidate) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Candidate) GetImgName() string {
	if x != nil {
		return x.ImgName
	}
	return ""
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min   int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max   int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_votingconfig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_votingconfig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_votingconfig_proto_rawDescGZIP(), []int{3}
}

func (x *Params) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Params) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Params) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_votingconfig_proto protoreflect.FileDescriptor

var file_votingconfig_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x62, 0x22, 0xf3, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x31, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c,
	0x74, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x74, 0x32, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0a,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x6e, 0x43, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x6e, 0x43,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x6f, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x6b, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x6b, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x76, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x76, 0x6d, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x0c, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x44, 0x0a, 0x08, 0x54, 0x69,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x63,
	0x22, 0x77, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x6d, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_votingconfig_proto_rawDescOnce sync.Once
	file_votingconfig_proto_rawDescData = file_votingconfig_proto_rawDesc
)

func file_votingconfig_proto_rawDescGZIP() []byte {
	file_votingconfig_proto_rawDescOnce.Do(func() {
		file_votingconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_votingconfig_proto_rawDescData)
	})
	return file_votingconfig_proto_rawDescData
}

var file_votingconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_votingconfig_proto_goTypes = []interface{}{
	(*Config)(nil),    // 0: voting.util.pb.Config
	(*TimeInfo)(nil),  // 1: voting.util.pb.TimeInfo
	(*Candidate)(nil), // 2: voting.util.pb.Candidate
	(*Params)(nil),    // 3: voting.util.pb.Params
}
var file_votingconfig_proto_depIdxs = []int32{
	1, // 0: voting.util.pb.Config.time:type_name -> voting.util.pb.TimeInfo
	2, // 1: voting.util.pb.Config.candidates:type_name -> voting.util.pb.Candidate
	3, // 2: voting.util.pb.Config.params:type_name -> voting.util.pb.Params
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_votingconfig_proto_init() }
func file_votingconfig_proto_init() {
	if File_votingconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_votingconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votingconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votingconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_votingconfig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_votingconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_votingconfig_proto_goTypes,
		DependencyIndexes: file_votingconfig_proto_depIdxs,
		MessageInfos:      file_votingconfig_proto_msgTypes,
	}.Build()
	File_votingconfig_proto = out.File
	file_votingconfig_proto_rawDesc = nil
	file_votingconfig_proto_goTypes = nil
	file_votingconfig_proto_depIdxs = nil
}
